# Generated by Django 5.1.2 on 2024-10-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=64)),
            ],
        ),
    ]
