# Generated by Django 5.1.2 on 2024-10-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_timestamp',
            field=models.DateTimeField(default='2024-01-11 00:00:12.000'),
            preserve_default=False,
        ),
    ]
